defaults: &defaults
  working_directory: ~/circleci_python_workshop
  docker:
    - image: circleci/python:3.6.1

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workshop:
          root: .
          path: .

  python_dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
        at: .
      - restore_cache:
          keys:
            -py-deps-{{ checksum "requirements.txt "}}
      - run:
        name: Install Dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
        save_cache:
          key: -py-deps-{{ checksum "requirements.txt "}}
          path:
          - ./venv

  static_analysis:
    <<: *defaults
      steps:
        - attach_workspace:
          at: .
        - restore_cache:
            keys:
              -py-deps-{{ checksum "requirements.txt "}}
        - run:
          name: Run static Analysis
          command: |
            python3 -m venv venv
            . venv/bin/activate
            flake8 test_fizzbuzz.py
          save_cache:
            key: -py-deps-{{ checksum "requirements.txt "}}
            path:
            - ./venv

  unit_test:
    <<: *defaults
      steps:
        - attach_workspace:
          at: .
        - restore_cache:
            keys:
              -py-deps-{{ checksum "requirements.txt "}}
        - run:
          name: Run static Analysis
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python test_fizzbuzz.py
          save_cache:
            key: -py-deps-{{ checksum "requirements.txt "}}
            path:
            - ./venv
workflows:
  version: 2
  circle_ci_workshop_pipleline:
    jobs:
      - checkout_code
      - python_dependencies:
        requires:
          - checkout_code
      - static_analysis:
        requires:
          - python_dependencies
      - unit_test:
        requires:
          - python_dependencies
            