default: &default
  working_directory: ~/circleci_python_workshop
  docker:
    - image: circleci/python:3.6.1
workflow:
  version: 2
  checkout_code:
    <<: *default
  steps:
    - checkout
    - persist_to_workshop:
        root: .
        path: .

python_dependencies:
  <<: *default
  steps:
    - attach_workspace:
      at: .
    - restore_cache:
        keys:
          -py-deps-{{ checksum "requirements.txt "}}
    - run:
      name: Install Dependencies
      command: |
        python3 -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt
      save_cache:
        key: -py-deps-{{ checksum "requirements.txt "}}
        path:
        - ./venv

static_analysis:
  <<: *default
    steps:
      - attach_workspace:
        at: .
      - restore_cache:
          keys:
            -py-deps-{{ checksum "requirements.txt "}}
      - run:
        name: Run static Analysis
        command: |
          python3 -m venv venv
          . venv/bin/activate
          flake8 test_fizzbuzz.py
        save_cache:
          key: -py-deps-{{ checksum "requirements.txt "}}
          path:
          - ./venv

unit_test:
  <<: *default
    steps:
      - attach_workspace:
        at: .
      - restore_cache:
          keys:
            -py-deps-{{ checksum "requirements.txt "}}
      - run:
        name: Run static Analysis
        command: |
          python3 -m venv venv
          . venv/bin/activate
          python test_fizzbuzz.py
        save_cache:
          key: -py-deps-{{ checksum "requirements.txt "}}
          path:
          - ./venv

  circle_ci_workshop_pipleline:
  jobs:
    - checkout_code
    - python_dependencies:
      requires:
        - checkout_code
    - static_analysis:
      requires:
        - python_dependencies
    - unit_test:
      requires:
        - python_dependencies
          